Universal-Debloater-Alliance/universal-android-debloater-next-generation

- Cargo.lock
- Cargo.toml
- src/gui/style.rs
Regenerated lockfile, also added iced directly. This should get rid of dependabot issue about atty
> Updated lockfile

- resources/assets/uad_lists.json
All other patches made by anonymousWP
> Anonymous wp all remaining patches

- resources/assets/uad_lists.json
Let's see if we can restart UAD :)
> pkg: com.telus.myaccount

- CHANGELOG.md
- src/core/sync.rs
- src/core/uad_lists.rs
> ADB get all packages fix

- CHANGELOG.md
- resources/assets/uad_lists.json
> added android.autoinstalls.config.Xiaomi.model

- CHANGELOG.md
- resources/assets/uad_lists.json
> Updated camera description

- Cargo.lock
- Cargo.toml
> OpenGL Fix

- resources/assets/uad_lists.json
Adds new package for MediaTek devices and the POCO Launcher resources, IMS Service Entitlement feature, UWB communication feature, Mediatek Duraspeed, and Mediatek Soc Package.
> pkg: Add Mediatek Soc package and AOSP package

- resources/assets/uad_lists.json
> pkg(`com.qualcomm.qcrilmsgtunnel`): change removal and description

- resources/assets/uad_lists.json
> pkg(`com.google.android.googlequicksearchbox`): improve description

- src/core/sync.rs
Reverse #18 to list only system packages
> only list system packages

- src/gui/mod.rs
> Reduced startup window size

- README.md
I added installation instructions for
-Gentoo Linux
-NixOS
-Alpine Linux & FreeBSD
-Fedora Linux
> Add installation instructions for more Linux distributions in the README

- resources/assets/uad_lists.json
added more packages and used from old pull requests add/changes packages, descriptions.
> Added/Updated packages, descriptions

- resources/assets/uad_lists.json
> pkg(`com.samsung.android.app.contacts`): add details to description

- resources/assets/uad_lists.json
- `com.sec.android.app.SecSetupWizard`
- `com.sec.phone`
> pkg(samsung): change description and removal

- CONTRIBUTING.md
This PR adds a guide (`CONTRIBUTING.md`) where we explain what methodologies we use, along with some other guidelines that we prefer you (as a contributor) to use.
> docs(contributing): add `CONTRIBUTING.md`

- resources/assets/uad_lists.json
- Fix a few typos and bad grammar
> doc: fix typos and bad grammar

- README.md
> docs(readme): add Discord invite

- resources/assets/uad_lists.json
Fixes the grammar in the descriptions for a handful of apps I came across.
> fix: grammar and repetitive descriptions

- resources/assets/uad_lists.json
Remove confusing information, and add better description.
> Update description of `com.samsung.android.app.omcagent`

- .github/workflows/build_artifacts.yml
> feat: add checksum making commands

- resources/assets/uad_lists.json
> pkg(`com.mi.android.globalminusscreen`): update description

- README.md
Leftover from 0x192's repo. As we're now with multiple people, this no longer fits.
> docs(readme): remove singular language

- resources/assets/uad_lists.json
> pkg(simple-apps): remove all recommendations of Simple apps

- resources/assets/uad_lists.json
> fix uad_lists.json

- src/core/utils.rs
> feat(ui): change default theme to Dark

- README.md
Related change: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/FAQ#help-my-phone-is-stuck-in-a-bootloop
> docs(readme): add FAQ item

- .github/workflows/build_artifacts.yml
> fix: typo in build_artifacts.yml

- resources/assets/uad_lists.json
> Google Chromecast APKs

- resources/assets/uad_lists.json
- [pkg(com.samsung.android.smartface): fix JSON-error](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/commit/b0e2ca83998124c21655691335e2652534e229fc)
- [pkg(com.samsung.android.svcagent): change description](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/commit/46bc33192cf4b9b31b253396f08e4f293b6b5453)
> pkg(samsung): update descriptions of `com.samsung.android.smartface` and `com.samsung.android.svcagent`

- resources/assets/uad_lists.json
- [pkg(samsung): add com.samsung.android.wallpaper.res](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/commit/15f1c859654a18c014ea1842eff6b0df75b4cc06)
- [pkg(com.samsung.android.photoremasterservice): add package](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/232/commits/aba6af34868580d4f5b44014fd82180f86ba4f6c)
> pkg(samsung): add two packages

- resources/assets/uad_lists.json
Judging by the description, removing this package somewhere may break some functionality
> com.google.android.deskclock now Advanced

- resources/assets/uad_lists.json
The reason is in the description of the application, perhaps it’s even Expert
> com.google.android.apps.wellbeing now advanced

- .github/ISSUE_TEMPLATE/add-new-package-s-.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/update-apps-description-or-recommendation.md
This is an attempt to streamline issue titles for in the future, that will hopefully be followed by (future) contributors. If you have a different stance/opinion about this, let's discuss it here.
> chore(issue-templates): improve default title text

- .github/workflows/release.yml
> feat(ci): changed release notes to use github's auto generated one.

- resources/assets/uad_lists.json
> webview package description update

- resources/assets/uad_lists.json
I am guessing there's still a lot more of them. Perhaps some CI to check for typos in uad list on every PR could be considered, but it might pick up a lot of junk from the pkg names..
> fix: update uad list typos

- resources/assets/uad_lists.json
> fix: update desc / typos of uad_list

- resources/assets/uad_lists.json
Package for secret codes. Safe to remove
> pkg: add `com.longcheertel.secretcode`

- resources/assets/uad_lists.json
Thanks to thatgreenpie for sharing unlisted bloat apk's.
> pkg: add Infinix packages

- CONTRIBUTING.md
This PR contains the following and is subject to change (based on feedback).
**New headers with information**
- Branching strategy
- Commit messages
- Checklist before we release
- Faulty releases
> docs(contributing): add new headers and guidelines

- resources/assets/uad_lists.json
> pkg(huawei): update descriptions

- resources/assets/uad_lists.json
Removed some google play links that not exist,
added packages,
changed some descriptions
> pkg(huawei): add packages and change descriptions/removals

- .github/release.yml
A refactor doesn't always fix a bug, but a refactor does always change the code. However, changing code doesn't mean its function will change. Feature label doesn't exist, so replaced it by enhancement.
> release(changelog): add and remove labels

- resources/assets/uad_lists.json
> fix: update descriptions of pkgs

- resources/assets/uad_lists.json
Related: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/320
>  pkg(com.hoffnung): warn user to disable instead of uninstall

- resources/assets/uad_lists.json
- [pkg(xiaomi): add cn.wps.moffice_eng](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/commit/57d9cdd50be145d90f9e17299bddb1f9cc774d12)
- [pkg(xiaomi): add com.xiaomi.aicr](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/commit/f549d338554627a2123a269bad2face55cc77796)
> pkg(xiaomi): add packages

- README.md
Related: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/How-to-contribute/_history.
> docs(readme): clarify what the Wiki is used for

- resources/assets/uad_lists.json
more information, less disinformation
> pkg: add Xiaomi packages and improve documentation/removals of some other packages

- resources/assets/uad_lists.json
- src/core/update.rs
- src/gui/mod.rs
- fixed json file
- added more verbose explanation where update failed in update.rs file
resolves #370
> bug(uad-list): json parsing error

- resources/assets/uad_lists.json
More than 100 packages were still assigned to the `Pending` list. I now assigned all of them to a fitting `List`.
> pkg: add many packages to list (before pending)

- src/gui/mod.rs
- messed up placement correct placement, now it fixed toggle
> fix(ui): toggle all checkboxes and review button is not updated on selected device

- resources/assets/uad_lists.json
uad update list [HeyTap Melody(Oppo)]
> pkg(com.heytap.headset): add package and change removal of `com.oplus.melody`

- src/core/update.rs
- src/core/utils.rs
- src/gui/views/about.rs
- src/gui/views/settings.rs
This makes it look more neat. Putting spaces between colons look ugly and is probably done by 0x192. It's common for French people to put spaces between colons and exclamation marks etc.
---
Not sure what label to assign.
> style: remove redundant spaces and fix misc typos

- resources/assets/uad_lists.json
Some Pending Packages Explained, Added more unlisted apps.
> pkg(samsung): add Samsung packages and improve documentation of some others

- src/gui/views/list.rs
This PR moves the ready state view, control panel and error modal into their own subroutines.
> refactor: reduce cycolmatic complexity

- resources/assets/uad_lists.json
added info about these packages ->
com.transsion.manualguide
com.transsion.aiwallpaper
com.transsion.aivoiceassistant
com.transsion.aisettings
> added new transsion packages

- src/core/sync.rs
- src/core/utils.rs
- src/gui/mod.rs
- src/gui/views/list.rs
Code coverage fix for https://app.deepsource.com/gh/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issue/RS-W1015/occurrences
> fix(codecov): move serial environment variable name into constant

- resources/assets/uad_lists.json
- [pkg(oneplus): add com.oplus.pantanal.ums package](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/commit/79abf25e6ebb88fdf675c39ca7705edd07004203)
- [pkg(com.oplus.nas): change removal and improve description](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/commit/271fd4886600cb34028d9b395f4ba0aa4dc31adb)
> pkg(oneplus): add OnePlus package

- resources/assets/uad_lists.json
Issues #299, #450, #454, #461, #464, #465, #467 and "com.samsung.android.globalpostprocmgr", "com.samsung.android.audiomirroring", "com.aura.jet.att", "com.aura.oobe.att" from discord.
> pkg: add packages, fix descriptions from issues section and from discord

- resources/assets/uad_lists.json
- [pkg(me.phh.treble.app): add package for GSI ROM](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/commit/589ecbb9153187325413082fabde57d61c9b5a28)
- [pkg(com.android.settings.os.overlay): remove duplicate](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/commit/ad0d480fac3722486f0d6618aaec80771e02b9f9)
Fixes #468.
> pkg(me.phh.treble.app): add package for GSI ROM

- resources/assets/uad_lists.json
These were really hurting my eyes.
Any ETA on a new release? Last one has been at the end of march, and there has been quite a lot changes since then.
> pkg(samsung/qualcomm): update descriptions

- resources/assets/uad_lists.json
also some styling, like \n before link
> pkg(com.android.camera): fix typos in description

- resources/assets/uad_lists.json
make it more coherent and replace dead URL
> pkg(com.motorola.VirtualUiccPayment): update description

- resources/assets/uad_lists.json
Add 3 pre-installed packages on Sony Xperia AU network
> pkg(sony): add packages

- src/core/config.rs
- src/core/theme.rs
- src/core/utils.rs
closes #182
ℹ️ https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/182#issuecomment-2208347197
> feat(theme): follow system theme by default

- resources/assets/uad_lists.json
Added com.preff.kb.xm. Pre installed keyboard app on xiaomi (hyperso).
> pkg(com.preff.kb.xm): add package

- .github/workflows/ci.yml
fixes #519
https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/519#issuecomment-2198124323
> build(ci): treat warns as warns

- resources/assets/uad_lists.json
- https://thehackernews.com/2024/08/google-pixel-devices-shipped-with.html
- https://www.apkmirror.com/apk/verizon-vz/verizon-store-demo-mode/verizon-store-demo-mode-retail-demo-mode-release/verizon-retail-demo-mode-retail-demo-mode-android-apk-download/
> pkg(com.customermobile.preload.vzw): update description with security finding

- resources/assets/uad_lists.json
- Firefox 129
- Chrome uninstalled
- G Play Services v24.32
- G Services Framework v12
- Android 12.0
- One UI 4.1
- Model: SM-A315G
Can store and use passkeys
> pkg(com.android.chrome): add note about passkeys to description

- resources/assets/uad_lists.json
This closes issues #589, #590, and #591.
> pkg(samsung): add packages

- resources/assets/uad_lists.json
stock android accessiblity setting afaik but in my lg v30 the package is named settings instead of setting
> pkg(com.android.settingsaccessibility): add package

- src/core/sync.rs
> docs(public-functions): add documentation for public functions in `sync.rs`

- resources/assets/uad_lists.json
CC: @Rudxain, because he was actively participating in the linked issue.
> pkg(com.hoffnung): improve description

- resources/assets/uad_lists.json
> pkg(Alibaba): add AliExpress

- resources/assets/uad_lists.json
Added com.taboola.scoop (Wallpaper Carousel)
> pkg(com.taboola.scoop): add wallpaper carousel package

- resources/assets/uad_lists.json
> pkg(com.android.wallpaperbackup): fix typo in description

- resources/assets/uad_lists.json
(`com.samsung.android.aircommandmanager`)
0x192/universal-android-debloater#783
> pkg(com.samsung.android.aircommandmanager): "ACM" -> "FACM"

- resources/assets/uad_lists.json
com.samsung.android.app.dtv.dmb
> pkg(com.samsung.android.app.dtv.dmb): add package

- resources/assets/uad_lists.json
Updates:
- `com.samsung.android.mdecservice`
- `com.samsung.klmsagent`
> pkg(samsung): fix grammar and formatting for some Galaxy packs

- resources/assets/uad_lists.json
> pkg(com.android.phone): improve description and change removal type

- resources/assets/uad_lists.json
Change-Id: I00343c9c16197c6be8c44fddf167cc05186fd978
> pkg(google): improve description, add package

- resources/assets/uad_lists.json
Partially reverts #86
See Universal-Debloater-Alliance/universal-android-preinstalled-lists#3
> pkg(distro): remove community distros

- Cargo.toml
- src/core/adb.rs
- src/core/config.rs
- src/core/save.rs
- src/core/sync.rs
- src/core/theme.rs
- src/core/uad_lists.rs
- src/core/update.rs
- src/core/utils.rs
- src/gui/mod.rs
- src/gui/style.rs
- src/gui/views/about.rs
- src/gui/views/list.rs
- src/gui/views/settings.rs
- src/gui/widgets/modal.rs
- src/gui/widgets/navigation_menu.rs
- src/gui/widgets/package_row.rs
- src/main.rs
0. `cargo fix --edition`
1. Manually update `Cargo.toml`
2. `cargo fmt`
> build(rust-edition): migrate to Rust 2024

- src/core/adb.rs
- src/gui/views/about.rs
- Continuation of #894
- Fixes compilation error in non-debug builds: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/894#issuecomment-2711653274
> fix: fix all `cfg` shenanigans

- resources/assets/uad_lists.json
Update edge panel entry and remove outdated parental control description.
> pkg(cnn): remove duplicate

- resources/assets/uad_lists.json
Change-Id: Ifbbaa8f3486129dbed464c5818b812ff8259764b
> pkg(com.android.role.notes.enabled): add warning regarding Developer Options

- resources/assets/uad_lists.json
Revise descriptions for clarity and update removal behavior to indicate potential risks for specific packages.
> pkg(com.android.global): update description and removal behaviour

- resources/assets/uad_lists.json
Add dependencies related to Private space on Pixel devices and update their removal status from "Recommended" to "Advanced."
> pkg(oem): update descriptions and change removal status for dependencies related to Private space on Pixel devices

- src/core/sync.rs
- Fix a typo 
- Remove unnecessary semicolon
> fix(sync): minor fixes

- resources/assets/uad_lists.json
> pkg(scope): Issues with SIM Manager, Package Removal, and Performance

- resources/assets/uad_lists.json
> pkg(com.oem.euiccpartnerapp): breaks sim manager Moto G 5G 2024

- resources/assets/uad_lists.json
> pkg(scope): com.samsung.android.providers.trash Samsung Voice Recorder Crash

- resources/assets/uad_lists.json
> pkg(scope): com.google.android.safetycenter.resources

- resources/assets/uad_lists.json
> pkg(com.motorola.livewallpaper3.prebuilt.*): add Motorola Prebuilt themes

- resources/assets/uad_lists.json
> pkg(com.google.android.tungsten.setupwraith): change removal and description

- resources/assets/uad_lists.json
Enhance the descriptions of several packages to provide clearer information about their functionality.
> pkg(miui, aosp): change description and removal

- resources/assets/uad_lists.json
UnListed Oem App called com.mi.appfinder updated (Xaiomi Poco)
> pkg(Xiaomi): add App Finder

- resources/assets/uad_lists.json
Fix and updated https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/844
> UPDATED: pkg(samsung, cyrus, google): add packages 
