- resources/assets/uad_lists.json
Adds `com.android.cellbroadcastreceiver.module`.
As seen [here](https://github.com/0x192/universal-android-debloater/pull/883).
> pkg: `com.android.cellbroadcastreceiver.module`

- resources/assets/uad_lists.json
This pull request adds new Wi-Fi related packages, custom Bluetooth overlay package, Google system packages, and systemui package. It also includes Android RRO overlays for AOSP and MIUI. Additionally, there are new packages for Tethering module and updated descriptions for existing packages.
> pkg: Add Wi-Fi, Bluetooth, and system packages

- Cargo.toml
- src/gui/widgets/modal.rs
Continues the work of @Frigyes06. 
For modern versions of iced, using ``iced::advanced`` will do when creating custom widgets. Since ``iced_native`` is only used by ``modal.rs``, I have removed that unused dependency.
The program now compiles, but I haven't tested it thoroughly.
> Update modal widget to run on iced 0.10.0, remove iced_native

- Cargo.lock
- Cargo.toml
- src/gui/mod.rs
- src/gui/style.rs
- src/gui/widgets/modal.rs
- src/gui/widgets/navigation_menu.rs
Per https://github.com/Universal-Debloater-Alliance/universal-android-debloater/blob/main/CONTRIBUTING.md, we're abandoning `dev` as we found it was merely an unnecessary parallel branch that hindered our development.
From now on, all PRs — even members' — will be against `main`, which can be considered the "trunk" of this repository.
> chore: clean up dev to merge into main and then delete

- src/gui/views/settings.rs
Fixes #116.
Continuing from https://github.com/Universal-Debloater-Alliance/universal-android-debloater/pull/97#issuecomment-1868580290.
When content exceeds window height:
When content fits within window:
> feat(settings): made it scrollable

- resources/assets/uad_lists.json
- Removing this `com.miui.miinput` package breaks `Gesture shortcuts` under `Additional settings`.
- The same issue has been discussed in [here](https://www.reddit.com/r/Xiaomi/comments/tpiox1/comment/jprokou/).
> [CHG] Move the "com.miui.miinput" package to the "Advanced" category.

- src/gui/views/list.rs
- Removes "Select all" and "Unselect All" button from the bottom row
- Adds a checkbox to the top row in line with the package checkbox entries for a more intuitive "select all" and "deselect all" experience
> feat(ui): move select and deselect all actions to more intuitive checkbox

- src/gui/views/list.rs
- Adds background against tooltip text for reading ease
- Adds a little bit of gap between the checkbox and tooltip
> feat: add the default styling and gap to tooltip

- src/gui/views/list.rs
- src/gui/widgets/navigation_menu.rs
- Add a tooltip that says "Refresh apps" for the refresh symbolic button
- Remove useless divider between the search box and the remaining buttons
> feat(ui): remove useless divider and add a tooltip for the refresh button

- .github/workflows/build_artifacts.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- src/core/update.rs
- src/core/utils.rs
- src/main.rs
We should've reviewed #124 more carefully, as most of this PR is in reaction to it.
Fixed:
- #124 changed cache/log directory to `uad-ng`, which I don't think we wanted (can be argued as bloat).
Continuing to use `uad` would be preferable as users would have to manually delete the old one otherwise.
- The `build_artifacts` & `release` workflows were broken because they still used `uad_gui`.
- Log-level configuration for our own crate (uad) still used `uad_gui`
Additional changes in this PR:
- `release` workflow will no longer run at all on a normal push
This workflow just creates pre-releases if we've pushed a tag. However, with the previous configuration, only the sub-step of creating a release was skipped, but the other steps for building & downloading artifacts were running every …
> Fix broken CI & code stuff after project name change

- LICENSE
- README.md
It's unnecessary as everyone is already familiar with the name. Barely anyone uses the CLI-version now.
> docs: remove explicit mention of 'GUI'

- src/core/sync.rs
- Select optional user struct based on SDK version conditional using the `then_some` method on the conditional itself
-  Pass the optional to the request builder
- No user-facing changes
> refactor: select optional user struct based on SDK version conditional

- src/core/utils.rs
- Use `if let` binding to get a package if it exists in the list and further access attributes
- No user facing changes
> refactor: use if-let binding for getting package attributes

- src/gui/mod.rs
- src/gui/views/list.rs
- src/gui/widgets/navigation_menu.rs
- Removes unused `String` from `LoadingState` variants that never use the inner string
- Use the derive macro to specify the default value instead of manual implementation
> refactor: remove unused string inside enum variants

- src/core/sync.rs
- Use default values with `unwrap_or_default` on optional values instead of explicitly constructing values
- Remove redundant clippy linting directive
- No user facing changes
> refactor: use default values with `unwrap_or_default`

- .github/workflows/release.yml
Draft PR only because I'm not sure if skipping the `build` job would be better, or configuring the workflow itself to run only on tag pushes (instead of paths).
Example config for tags-only:
```yaml
on:
push:
branches:
- main
tags:
- v?[0-9]+.[0-9]+.[0-9]+ # important part
- '!dev-build' # not dev-build
```
With this config, we won't need to have the `if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')` condition at all.
> fix(workflow): release.yml workflow's build job runs when it shouldn't

- src/gui/views/settings.rs
The backup struct for a given device is created regardless of its presence in the configuration file. This PR changes the code so as to build the structure first, then check the config file.
> refactor: create a backup struct ahead of time

- src/core/sync.rs
Fixes: #188
The program prematurely exits with a status code of 1 when ADB is not found.
> fix: exit when adb is not found

- src/core/uad_lists.rs
- src/gui/views/list.rs
- create summary struct to be able to name fields (instead of `.0` and `.1`)
- use cheaper 5 element slice for summary entries instead of hashmap
> feat: create summary struct to describe summary entries

- src/gui/style.rs
- src/gui/widgets/navigation_menu.rs
- don't force user update by showing only Update tab without showing Apps tab
> feat(ui): don't force users to update without showing 'Apps' tab

- src/core/update.rs
Fixes #224
- The `v` prefix from the version name is ignored if it exists. Should prevent erroneous update version.
> fix: strip `v` version prefix when checking for updates

- Cargo.toml
- src/main.rs
fixes: #237
While `#![windows_subsystem = "windows"]` is fine since we don't want the app to create the terminal on startup, this has the consequence of outright disabling terminal output, even if we launch it from the console.
The proposed fix uses [`windows-sys`](https://crates.io/crates/windows-sys) to attach the process' stout to any available console.
Reference: https://learn.microsoft.com/en-us/windows/console/attachconsole
While this introduces a new dependency, since they're raw FFI calls for the windows-api, they should add little to no overhead.
> fix: allow the app to display logs when launced from the terminal on windows

- Cargo.lock
- src/main.rs
Applies a clippy lint so that tests can proceed.
> lint: apply clippy suggestions

- resources/assets/uad_lists.json
POCO X3 NFC 
MIUI GLOBAL 14.0.2
``com.miui.wmsvc``: This one didn't cause bootloop for me, and I don't think it has broken anything as well. I checked other resources and this package is always documented and reported as safe to remove. App description can be updated to *it is safe to disable/uninstall*
[source](https://github.com/0x192/universal-android-debloater/issues/137)
[source](https://rootmygalaxy.net/xiaomi-bloatware-list/)
[source](https://www.reddit.com/r/PocoPhones/comments/jc5rlr/list_of_safe_to_uninstall_system_apps/) (this one claims removing the package may potentially disable widevine L1)
```
com.miui.security.add
com.miui.securitycenter
com.miui.securitycore
```
Removing these will cause bootloop for the majority of the users (they do on my device), and theyre listed as …
> Change package descriptions and categories

- src/core/sync.rs
fixes regression introduced in 6ffba9d40efad82c8129904ef38385c9ae30f288
> fix: pass user flag when sdk version is 21 or above

- resources/assets/uad_lists.json
Duraspeed mentioned here is just an UI component. As such, uninstalling it may lead to unintended consequences.
> Update uad_lists.json, Duraspeed info

- .github/ISSUE_TEMPLATE/documentation.md
Currently, there's no issue template for documentational things, and since we've (consciously) disabled blank issues, it's hard to keep track of documentation that needs to be written. An alternative for this is to use GitHub Projects for this, but that's not as accessible.
> chore(issue-templates): add documentation template

- .github/workflows/build_artifacts.yml
The sha256 sums were overwriting the tarballs because folded block scalars (>) were used instead of literal block scalars (|).
Also added a step to install coreutils if on macos so we have sha256sum on the mac environment
> fix(ci): sha256sum errors and overwrites

- .github/ISSUE_TEMPLATE/3-add-new-packages.yml
- .github/ISSUE_TEMPLATE/5-update-apps-description-or-recommendation.yml
This prevented the label from being automatically assigned when an issue was created.
> chore(issue-templates): fix typos in labels

- src/gui/widgets/navigation_menu.rs
- moved buttons, so that they are consistent if device is not found vs found. Ln. nr. 101, 102
- changed wording for update info, on small window size previous wording takes a lot of screen and pushes buttons out of boundaries of window. Updated is not ideal, but takes less screen.
> feat(ui): consistent buttons placements and "update" wording

- src/core/sync.rs
- src/gui/mod.rs
- src/gui/views/list.rs
> feat(startup): inform user when ADB isn't installed

- src/gui/mod.rs
- fixed issues when feature: no-self-update flag was passed
resolves #308
> fix(app): unused variable 'res' when building with no-self-update

- src/gui/mod.rs
- fixed issue where if adb was installed and refresh button pressed, message about ADB not installed was still visible
> fix(startup): refreshing doesn't make the "adb not installed" message disappear

- src/gui/mod.rs
- src/gui/views/list.rs
Use if-else blocks instead of match for booleans
> refactor(app): use if-else instead of match over booleans

- .github/workflows/release.yml
Path was wrong, too much got axed when we were getting rid of /bin/
Tested in my fork
Fixes #380
> fix(ci): upload artifacts correctly

- src/core/sync.rs
- src/gui/views/list.rs
- src/gui/views/settings.rs
This is more or less scaffold code to display the raw error if an ADB command fails.
Related to #37
- We use an enum to classify these errors. Currently it only has one error type as `Generic`.
- Any ADB error will display a modal with the raw error trace of the ADB command itself.
> feat: graphically display error when adb command fails

- resources/assets/uad_lists.json
Removing this package breaks entering password on lockscreen (after initial boot)
I had to connect a physical keyboard, unlock my phone, and then restore the app again.
> pkg(com.facemoji.lite.transsion): add info about potential breakage on Infinix phones

- src/core/utils.rs
- src/gui/views/list.rs
- added back possibility to export current selection to txt file
- on successful export show modal
Resolves #300
> feat(backup): re-add export selection to text file

- src/gui/views/list.rs
- increased width of modal
- adjusted some column sizes
Resolves #121
> bug(ui): visual bugs in selection review

- .github/workflows/ci.yml
The incorrect filename caused the CI job to not run whenever a PR has been opened that made changes to the UAD list. `uad_list.json` was used instead of `uad_lists.json`.
> fix(ci): incorrect filename being used for UAD list

- resources/assets/uad_lists.json
Included things from issue #410 and huawei apps some apps move to unsafe. Named some from list Google to Aosp, because its the same app with different name. Required to WiFi work, apps move to Unsafe.
Incorrect name packages fixed.
Added one package from Miui OEM
Checked some Miui Unsafe or Expert apps again.
Changed removal place for some apps.
Some recommended apps to pixel phone not looks recommended (more expert, someone will need to check them). #441 #423 
Thats my big research uad_lists.json, it did not cost me a week.
> pkg: add packages, improve descriptions and removals

- .github/workflows/ci.yml
`- resources/assets/uad_lists.json` was missing here: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/blob/main/.github/workflows/ci.yml#L11. As you can see, the CI is not running for user-submitted PRs: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/492. This should definitely be running, as users also tend to sometimes make a mistake, therefore messing up the JSON.
This PR fixes that issue, so now it's running for every PR, not matter if it comes from our organization or not.
> build(ci): fix ci not running for user-submitted PR

- resources/assets/uad_lists.json
OnePlus 7, Oxygen OS 11.
Removing this package also removes the 'Tips & Support' on settings app.
> docs(com.oneplus.config): change description

- resources/assets/uad_lists.json
Removing this package causes calls to not work on my Verizon LG G6 (VS988).
> pkg(com.lge.ims): change description and removal

- Cargo.lock
- Cargo.toml
- src/core/config.rs
- src/core/save.rs
- src/core/sync.rs
- src/core/theme.rs
- src/core/utils.rs
- src/gui/mod.rs
- src/gui/views/list.rs
- src/gui/views/settings.rs
- src/gui/widgets/modal.rs
- fixed some deepsource issues
Resolves #173
> feat(backup): add ability to export uninstalled packages with their description

- src/core/save.rs
- src/core/utils.rs
- src/gui/mod.rs
- src/gui/views/settings.rs
> hotfix(settings): patch regression and refactor a bit

- resources/assets/uad_lists.json
Removing Security apps not brick deep sleep, but doing anything on phone feels like more drain battery than before.
> pkg(miui): change descriptions and removals based on potential bootloop

- .github/ISSUE_TEMPLATE/1-bug-report.yml
operating-sys is required because UAD is only officially supported for 3 OSes.
desktop-environment and window-manager are suggested, because they may help debug GUI problems
> chore(bug-template): Include OS, WM, and DE

- resources/assets/uad_lists.json
Added that disabling om.google.android.googlequicksearchbox also breaks Google Lens
> pkg(com.google.android.googlequicksearchbox): improve description

- resources/assets/uad_lists.json
As this is a critical hot-fix, I've temporarily enabled bypassing for administrators so we do not need to wait for approval from another team member.
> fix(uad_lists): add missing quotes

- resources/assets/uad_lists.json
Removing this package causes the clock app to crash when trying to set an alarm to a specific date. Tested on my LG G6.
> pkg(com.lge.sui.widget): change description and removal

- src/core/update.rs
- src/core/utils.rs
- src/gui/mod.rs
- src/gui/views/about.rs
- src/gui/views/list.rs
- src/gui/views/settings.rs
Closes #598
I decided to do an opportunistic refactoring of the app name, because this cmd:
```sh
grep -ri '"[^"]*UAD-ng[^"]*"' src/
```
printed too many lines
> refactor(app_id): specify `iced::Settings.id`

- resources/assets/uad_lists.json
- Updates description to warn about likely boot-loops, and adds a link as backing source.
- Previous `removal` was totally inaccurate. It should've been `Expert` as bare minimum.
- Minor formatting of desc.
> pkg(infinix): inform about bootloop and change `removal` to `unsafe`

- src/core/sync.rs
Addresses #401 
- Reuse `user_flag` function instead of checking optional with match block
- Defer to `pm block` and `pm clear` for SDK versions below 19
> fix: use `pm block` and `pm clear` for sdk versions below 19

- Cargo.toml
https://doc.rust-lang.org/cargo/reference/profiles.html
> build(ci): optimize Cargo `release` for program

- resources/assets/uad_lists.json
Funmax is Chinese bloatware included by Xiaomi, it has lots of permissions by default, but isn't required for anything, so it can safely be removed.
> pkg(com.mig.play.games): add Funmax package

- src/core/config.rs
- src/gui/style.rs
Looks like for MacOS we need to allow `bright.surface` to be black. This seems to have fixed it.
> build(ci): fix macOS linting failing

- .github/ISSUE_TEMPLATE/1-bug-report.yml
Why did we not have this earlier? 💀
BTW, since ADB typically comes bundled as part of the SDK Platform Tools, there's a **another version number**. I omitted it from the `placeholder`, because it doesn't seem necessary
> chore(issue-template): add ADB version field for bug-report

- resources/assets/uad_lists.json
The "com.xiaomi.market" package should be categorized as Advanced:
- It enables installation of the Google Play Store.
- It facilitates updates for essential system applications, such as the System Launcher.
> pkg(com.xiaomi.market): categorize it as Advanced

- resources/assets/uad_lists.json
- closes #762
- Updates descriptions of:
- `com.samsung.android.location`: add breakage example and display-name.
- `com.sec.location.nsflp2`
- `com.samsung.locationhistory`: grammar
I want to test some Galaxy phones before merging this, to see how widespread this issue is
> pkg(samsung): improve S-location related descriptions

- resources/assets/uad_lists.json
- `com.samsung.android.themecenter`
- can't be disabled/uninstalled **at all** on Galaxy A31 (`SM-A315G`)
- can be uninstalled on Galaxy J3 Mission (`SM-J327VPP`). Provides built-in wallpapers
- `com.samsung.android.themestore`
- needed for viewing (and applying) built-in wallpapers on the J3
> pkg(samsung themes): add wallpaper breakage info, remove redundancy

- resources/assets/uad_lists.json
Hello,
as stated in the commit itself, removing this package also breaks the selection of ring tones. I also suspect that it may break ringtones all together and force the alarm to always be silent if the phone is restarted after removing it. I came to this conclusion from my brief test, the ringing did not work before restoring the package but did after I uninstalled it again, I'd consider this a pretty large issue (seeing as I almost missed school today because of it), however I have yet to confirm this. I am currently unable to test this, but I'll report with my findings as soon as I'm able to.
Just for clarity, the phone this is occurring on is a Redmi Note 13 running on MIUI 14.0.6, but I see no reason this would be a phone-specific or miui-version-specific issue.
Thank you.
> pkg(com.android.thememanager): improve description

- .github/workflows/build_artifacts.yml
This PR adds support for `macos-13`, which has an Intel CPU: https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories. Perhaps it's a good idea to version the `os` anyway.
> build(ci): add runner for MacOS with Intel CPU

- src/core/utils.rs
- src/gui/views/settings.rs
Continuation of #796. Needs testing, I can't because of [this](https://discord.com/channels/1168607797081022514/1207249059346260008/1328389228240961648).
> refactor: extract UNINSTALLED_PACKAGES_FILE_NAME_FORMAT into a const

- src/core/sync.rs
This reduces the need to connect a device just to test the UI. One could argue "this is bad, because you have to test the full UI, including the pack list", but that isn't always the case. We can use the "sync icon" button to manually retry the command anyways, so why be forced to wait 60s?
> feat(ADB): retry `adb devices` only 3 times in debug builds

- src/core/uad_lists.rs
[Quoting myself](https://discord.com/channels/1168607797081022514/1171387180409692160/1328128536715857971):
> [...] I'll also open a PR about the filters. It's bothering me that the "All"s are so ambiguous
>
> [...] It seems Iced automatically uses their `Display` implementations, so we have to edit those
**User-facing changes:**
The goal of this PR is to reduce the cognitive load of remembering filter positions, as the "All" options will now include the type of the filter (less ambiguity).
**Technical details:**
I'm afraid [editing `impl Display`s could cause serialization bugs](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/383#issuecomment-2581212023). However, [`Display` is not intended for …
> feat(ui): clearer "All" filters

- resources/assets/uad_lists.json
Share is a very important part of the core OS that hardly anyone would wish to disable. Updated the description to bring attention to the word Share and moved the package from "Advanced" to "Expert".
> pkg(com.android.intentresolver): improve description and change removal

- resources/assets/uad_lists.json
As of January 2025, I have to manually enable `com.miui.cloudservice` and `com.miui.micloudsync` so that data synchronization with Xiaomi Cloud works as expected. This feature is important for Xiaomi phone users in China since Xiaomi Cloud serves this market. More information is available at https://i.mi.com/.
> pkg(com.miui.cloudservice and com.miui.micloudsync): update description

- Cargo.lock
- Cargo.toml
- src/core/config.rs
- src/core/save.rs
- src/core/sync.rs
- src/core/theme.rs
- src/main.rs
- closes #756
- `config.rs` tests: Converts a comment to a module-level comment. Silences `unwrap_used` warning
- Merge some `use` imports, because `rustfmt` was re-ordering them, and to reduce redundancy
> refactor(deps): replace `static_init` by `LazyLock`

- src/main.rs
I've spent like an hour looking through Iced, and apparently there is no option to pass config to wgpu, it always picks settings from env:
https://docs.rs/iced_renderer/0.12.1/src/iced_renderer/compositor.rs.html#252
https://docs.rs/iced_wgpu/0.12.1/src/iced_wgpu/settings.rs.html#47
Also, for some reason, on my PC setting via WGPU_BACKEND=gl (either in terminal or using set_env) only fixes the issue when compiling with `--release`.
fixes #848
> fix: force `wgpu` to use dedicated/discrete graphics-card, to avoid Vulkan issues

- src/core/adb.rs
https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/851#issuecomment-2665850695
> fix: disable debug validation of pack-IDs

- .github/workflows/build_artifacts.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
This PR also upgrades the [GitHub release Action to v2](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/commit/60c89c887c2134733f68e82a876959a1db610802).
Artifact build results: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/actions/runs/13401871180
> build(ci): version-pin OS of runners

- Cargo.toml
- clippy.toml
- src/core/uad_lists.rs
- src/gui/views/about.rs
- src/gui/views/list.rs
- src/gui/views/settings.rs
- src/gui/widgets/mod.rs
- src/gui/widgets/navigation_menu.rs
- src/gui/widgets/package_row.rs
- src/gui/widgets/text.rs
I was only able to reproduce #523 with CJK characters. I tried using default Pop!_OS fonts from their PPA, but they were rendering normally.
This fix is based on the following comments:
- https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/523#issue-2378550768 the input field is rendered properly.
- https://github.com/iced-rs/iced/issues/2709 again, the input field is rendered properly, and the user notes "Adding shaping(text::Shaping::Advanced) makes the text render properly.".
fixes: #523
> fix: use advanced text shaping to prevent text being rendered as squares with certain fonts or CJK characters

- src/core/adb.rs
- src/core/sync.rs
Partially reverts #757
https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/650#issuecomment-2689463373
This prevents a potential bug, so I'm not sure if it's `refactor` or `fix`
> hotfix(sync:users): revert UID parsing

- src/gui/views/list.rs
This will be less misleading for users
> log: `error`->`warn`, if no device found

- .github/ISSUE_TEMPLATE/7-ci.yml
- .github/release.yml
- [chore(release): rename testing to ci](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/commit/cf03839ac78199621eb36b4e1d10e22c15b1a272)
- [chore(issue-template): add CI issue template](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/commit/aa6bd2417ad2be7d4c292bc2b3ee43417a52cecf)
- [ci(changelog): add and rename titles](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/883/commits/f7d77819c1d511513957a7384d9c4ea44607f483)
> chore(issue-template): add CI issue template

- CONTRIBUTING.md
- RELEASE.md
- [docs(release): move part of contributing to release file](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/commit/68a89d2473687fef5201570c938fd8b5ed44ccc6)
- [docs(release): add development process header](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/commit/0c86e71b06ce4965980113ae921a6b7b8f1c7b78)
- [docs(release): only mention UAD-ng version](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/889/commits/3c25c88109278b78fcdaca287376d61250306a09)
> docs(release): add development process header

- src/core/update.rs
> hotfix(self-update): differentiate between Intel and Apple Silicon on MacOS and update Windows binary name

- src/core/adb.rs
- src/gui/views/about.rs
- Closes #893
- Fixes a log formatting bug that should've been fixed [here](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/880/commits/1d657e899e66f758f034e3a10161bd3adac4ed81)
- Adds some `must_use` attributes to ADB methods
> feat(GUI:view:about): show `adb version`

- Cargo.lock
- Cargo.toml
- RELEASE.md
- [chore(release): bump version to 1.1.2](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/commit/1dbaeb56d8c3b6de1af7cee8148d6666ec9e6a2b)
- [docs(release): mention that we need to update Cargo.lock](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/commit/c649a261b39c267e34ad6b0b2db9436500aed870)
> chore(release): bump version to 1.1.2

- resources/assets/uad_lists.json
HyperOS devices are now the default for Xiaomi, so the impact of removal should focus on the impact re: HyperOS first (losing Quick Settings) and the impact re: MIUI second (gaining AOSP-style volume GUI).
> pkg(miui.systemui.plugin): improve description

- resources/assets/uad_lists.json
Enhance the description of Google Chrome to tell about Trichrome library which is update automatically when Chrome is update.
Starting from Android 10 (API29) Google Chrome, WebView and Trichrome library work together as a bundle, uninstall Google Chrome may break WebView function.
> pkg(com.android.chrome): update description for clarity on functionality

- .github/workflows/ci.yml
The `--all` flag is deprecated in favor of `--workspace` according to the docs. Either flag has no effect, since the entire workspace is 1 crate.
Ideally, we should also elevate `rustc` warns as errors by passing `RUSTFLAGS`, but I'm unsure what's the proper way to do so. See:
- [This S.O. thread](https://stackoverflow.com/questions/56870422/how-can-i-cause-compilation-to-fail-on-warnings-on-ci-and-have-extra-rustflags-s)
- Relevant issues:
- rust-lang/cargo#14948
- rust-lang/cargo#12739
Follow-up of: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/582#issuecomment-2282234568
> ci(cargo): improve linting

- src/main.rs
This canonicalizes the logs to be located at the same path. The reasoning for this is that the log-entries (lines) already contain date-time data, so naming the files according to the current date is redundant.
I've also taken the opportunity to append "ng" and make the name lowercase
> feat(log): single log-file (`const` name)

- resources/assets/uad_lists.json
I noticed the Data Usage option was gone on my oneplus phone after removing this package. I have updated the description, clarifying what it does and changed the removal level to Advanced.  Being able to block data usage for certain apps is a useful feature I think and should not be recommended.
> pkg(com.oplus.trafficmonitor): update description and removal

- src/core/adb.rs
- src/core/save.rs
- src/core/sync.rs
- src/core/update.rs
- src/core/utils.rs
- src/gui/mod.rs
- src/gui/views/list.rs
- src/gui/views/settings.rs
This fixes a warning by simplifying code, and makes a `fn` more idiomatic
> refactor: `list_available_backup_user` and `CommandType`->`PackageInfo`

- resources/assets/uad_lists.json
> pkg(scope): `com.sec.android.app.hwmoduletest` breaks after removing `com.samsung.android.providers.factory` on Samsung Galaxy phones

- src/gui/views/list.rs
As the title implies. Searching by the user-contributed descriptions helps when the package names are not at all descriptive of what it does.
> feat(search): allow searching in descriptions

- resources/assets/uad_lists.json
Removal of this package broke recents for me. Only after installing it back did my recents work. I double checked. Also checked the logcat that indeed applock is linked to the recents as a provider.
Logs:
```
06-21 14:05:26.040 10063  1632  1632 E AndroidRuntime: FATAL EXCEPTION: main
06-21 14:05:26.040 10063  1632  1632 E AndroidRuntime: Process: com.android.quickstep, PID: 1632
06-21 14:05:26.040 10063  1632  1632 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.quickstep/com.android.quickstep.RecentsActivity}: java.lang.SecurityException: Failed to find provider com.transsion.applock.provider for user 0; expected to find a valid ContentProvider for this authority
06-21 14:05:26.040 10063  1632  1632 E AndroidRuntime: 	at …
```
> pkg(com.transsion.applock): change description and removal

- resources/assets/uad_lists.json
Removing this package would render wifi local backup and restore functionality useless when you include backing up access points in ColorOS backup and restore settings. Unless you AP through other locations
Only tested for OPPO A5 2020, COLOROS 11
> pkg(com.coloros.wifibackuprestore): change removal and description

- Cargo.toml
This is `build` but it also ~a~effects `ci`. This has benefits:
- faster release builds by default (good for testing `cfg`s)
- `release` includes debug-info and panic-unwinding
It has the drawback that CI needs adjustment to allow users to get the `opt` version without building themselves
> build: split `release` profile into `opt`

- .cargo/config.toml
- Cargo.toml
- this uses whatever linker is installed on the system, until rust-lang/rust#140525 is merged
- additionally config something I missed in #1008
The reasoning for this is that `mold` should only be used for incremental builds. It's not appropriate if the user/dev wants more stability and less bugs.
If any `mold` contributor reads this, we appreciate the work being done on `mold` to improve this situation! It's just that we want to isolate sources of issues, as we already have enough problems with `wgpu`.
An alternative patch would be to edit CI to generate release-artifacts without `mold`, while keeping `mold` enabled in `.cargo/config.toml`
> build(cargo): don't use `mold`

- Cargo.lock
- Cargo.toml
- src/core/adb.rs
- src/core/config.rs
- src/core/save.rs
- src/core/sync.rs
- src/core/uad_lists.rs
- src/core/update.rs
- src/core/utils.rs
- src/gui/mod.rs
- src/gui/views/list.rs
- src/gui/views/settings.rs
- src/gui/widgets/modal.rs
Closes #623
I've only reviewed a few deps. I've `cargo run` and the app seems to work fine.
Iced-0.13 would require a big rewrite ([IMO, it was overdue](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/discussions/577#discussioncomment-11765767) anyways), but there are bugs (such as #432) and QoL improvements (for users and devs) that would be resolved by it.
We should also update `flake.lock`: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/622#issuecomment-2843440270
> build(deps): upgrade all dependencies but Iced

- src/gui/views/list.rs
**Pull Request Description:** This PR introduces a `Copy error` button to the ADB error modal. When an ADB operation fails, users can now easily copy the error message to their clipboard for troubleshooting or sharing. After clicking the button, the label changes to `Copied!` to provide immediate feedback. This enhancement improves user experience by making error reporting and support requests more convenient.
**_A demonstration of the new feature is attached below:_**
>  feat(ui): add copy button to copy error messages

- src/gui/views/list.rs
I experienced a crash when accidentally scrolling with the mouse on the text edit containing the add description. This hack fixed it for me, but it might cause issues in cases there's an actual need to scroll. Any ideas?
> fix(list-description-crash): add null action on scroll

- build.rs
- slightly improves build speed
- uses `embed_resource` according to the example-usage in its `README`
- fixes a compiler warn (`unused_must_use`)
> build(script): use `embed_resource` appropriately

- resources/assets/uad_lists.json
Due to it breaking the app drawer on Fire TV, I'd put it as advanced, as it renders the device a lot harder to use unless an alternative launcher is installed.
> move com.amazon.venezia to advanced
